### ISSUE TITLE
Not working, says it has published when it hasn't

### ISSUE THREAD

**Issue by bcannon08** [Southpaw1496/obsidian-send-to-ghost#6]
Hi, 
I double-checked my url and access token, and restarted Obsidian.
When I go to (draft) publish a note, it acts like it has sent to Ghost, but the banner shows the title of the first (already published) post on my website instead of the title of the note I was trying to send.  And nothing has actually been sent to Ghost.

I'm guessing this has to do with not having rewritten the plugin for the newer versions of Obsidian?  Just wondering if/when that will happen so I know if I can hold out hope of using the plugin again.

Thanks!

**Comment by SyndicatedPillbug** [comment]
I seem to be experiencing the same error.

**Comment by Southpaw1496** [comment]
I can't reproduce this on a simple note with just text in it, tested on the latest version of Ghost. Are either of you two making use of front matter, perhaps?

**Comment by huntercmeyer** [comment]
I am having the same issue.  Ghost version 5.129.1-0-g321feacb+moya and Obsidian version 1.8.10

No front matter in the article I'm trying to publish.  When I publish to ghost, it says "Insert name of top most post in Ghost" has been published successfully.  This happens when I tell Obsidian to "Send to Ghost" in the Command Palette, regardless of which article is open when I tell it to publish.

Thanks!

**Comment by Southpaw1496** [comment]
@huntercmeyer  I've just released 1.0.5, which has a "Debug" toggle in the settings that prints the request that is sent to Ghost and Ghost's response into the developer console. Can you install it, reproduce the issue, and send the contents of the Obsidian developer console to me? You can access the console using Ctrl-Alt-i (or Cmd-Alt-i on macOS). 

If you'd prefer not to post the Ghost response publicly, feel free to email me (git@southpaw1496.dev) instead.

**Comment by huntercmeyer** [comment]
Just emailed you.  Thanks!

**Comment by Southpaw1496** [comment]
Logs received, thanks so much!

Send to Ghost seems to be forming and sending its request correctly. So, this is either an issue with Ghost, or there's a slight possibility that the plugin is somehow sending a GET request instead of a POST one. I'm almost certain this isn't the case, because in the code it is very explicitly set to send a POST request.

Are you able to access the logs of your Ghost site? If you can, you can make a request and you should see a log entry that looks something like this:
```
[2025-07-14 16:15:49] INFO "POST /ghost/api/admin/posts/?source=html" 200 81ms
```
That will tell us the URL and method that Ghost thinks it received, and if it responded correctly. 

Another thing you can do is try running Ghost on a blank installation and see if that fixes it. If you're comfortable using Docker, this Docker Compose configuration should start up a fresh site and database for you to test at `http://localhost:2368`:
```yml
services:
  ghost:
    image: ghost:5.129.2
    depends_on: [mariadb]
    volumes:
      - ./Data/Ghost:/var/lib/ghost/content
    restart: always
    ports:
      - 2368:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      # this url value is just an example, and is likely wrong for your environ>
      url: http://localhost:3003
      
      database__client: mysql
      database__connection__host: mariadb
      database__connection__user: root
      database__connection__password: 'SET_TO_RANDOM_VALUE'
      database__connection__database: 'ghost'
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 'SET_TO_SAME_RANDOM_VALUE'
    volumes:
      - ./Data/MariaDB:/var/lib/mysql
```
Put it inside a file called `docker-compose.yml` in an empty directory, and then run `docker compose up -d` from the terminal to start the container.

Alternatively, you can [install Ghost locally](https://ghost.org/docs/install/local/), although this requires having Node.js and NPM installed (easily done with Homebrew - `brew install npm`).

If the blank install works correctly, it might be a reverse proxy you're using (like Nginx, Apache, or Caddy) or CDN (like Cloudflare or Fastly) is changing the method from POST to GET. It's very unlikely that a professionally hosted installation would do this (especially not Ghost Pro), but if you're hosting it yourself, there might be a misconfiguration somewhere.
